# Generated by Django 5.1.1 on 2024-09-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_infringement', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=4)),
                ('points', models.IntegerField()),
                ('penalty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
    ]
