# Generated by Django 5.1.1 on 2024-09-21 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 6, 15, 33, 21, 127928, tzinfo=datetime.timezone.utc)),
        ),
    ]
