# Generated by Django 5.1.1 on 2024-09-21 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0004_alter_payment_payment_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 6, 15, 55, 51, 566692, tzinfo=datetime.timezone.utc)),
        ),
    ]
