# Generated by Django 5.1.1 on 2024-09-21 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0005_alter_payment_payment_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 6, 16, 4, 34, 272780, tzinfo=datetime.timezone.utc)),
        ),
    ]
