# Generated by Django 5.1.1 on 2024-09-23 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0006_alter_payment_payment_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 8, 16, 35, 8, 366787, tzinfo=datetime.timezone.utc)),
        ),
    ]
