# Generated by Django 5.1.1 on 2024-09-24 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password_hash',
            new_name='password',
        ),
    ]
