# Generated by Django 5.1.1 on 2024-09-24 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_rename_password_hash_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='password_hash',
        ),
    ]
