# Generated by Django 5.1.1 on 2024-09-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_remove_user_password_hash_user_groups_user_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='user',
            name='license_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
