# Generated by Django 5.1.1 on 2024-09-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
