# Generated by Django 5.1.1 on 2024-09-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_remove_user_is_active_remove_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('motorist', 'Motorist'), ('official', 'Official')], max_length=10),
        ),
    ]
